[workspace]
members = [
    "lilyco-core",
    "lilyco-cli",
    "lilyco-tui",
    "lilyco-gui",
    "lilyco-graphite",
    "lilyco-mcp",
    "lilyco-macros",
    "lilyco-example",
    "lilyco-grep",
    "lilyco-mpkg",
    "lilyco-plc",
    "lilyco-brush",
    "lilyco-ffmpeg",
    "lilyco-files",
    "lilyco-binfmt",
    "lilyco-vision",
    "lilyco-ultra-ui",
    "lilyco-ultra-ui-example",
    "lilyco-letsgal",
    "lilyco-pet",
    "lilyco-bitnet",
    "lilyco",
]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lilyco-42/lilyco"
