[workspace]
members = [
    "lilyco-core",
    "lilyco-cli",
    "lilyco-tui",
    "lilyco-gui",
    "lilyco-mcp",
    "lilyco-macros",
    "lilyco-example",
    "lilyco-grep",
    "lilyco-brush",
    "lilyco-vision",
    "lilyco-ultra-ui",
    "lilyco-ultra-ui-example",
    "lilyco",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lilyco-42/lilyco"
